NAME = libftprintf.a

CC = cc 
CFLAGS = -Wall -Wextra -Werror

SRCS = ft_printf.c 
OBJS = ${SRCS:.c=.o}

all: ${NAME}

${NAME}: ${OBJS}
	ar rcs $@ $^

%.o: %.c
	${CC} ${CFLAGS} -c $^-o $@

clean:
	rm -f ${OBJS}

fclean: clean
	rm -f ${NAME}

re: fclean all