NAME = libftprintf.a
CC = cc 
CFLAGS = -Wall -Wextra -Werror

INCL = get_next_line.h
SRCS = get_next_line.c \
		get_next_line_utils.c
OBJS = ${SRCS:.c=.o}

all: ${NAME}

${NAME}: ${OBJS}
	ar rcs $@ $^

%.o: %.c {INCL}
	${CC} ${CFLAGS} -c $< -o $@

clean:
	rm -f ${OBJS}

fclean: clean
	rm -f ${NAME}

re: fclean all

.PHONY: all clean fclean re
